export const defaultData = {
    "families": [
        {
            "id": 1,
            "name": "Tons Suaves",
            "color": "#E8DDCB",
            "products": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                22,
                23,
                24
            ]
        },
        {
            "id": 2,
            "name": "Marrons e Cinzas",
            "color": "#6B4708",
            "products": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24
            ]
        },
        {
            "id": 3,
            "name": "Verdes",
            "color": "#169105",
            "products": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24
            ]
        }
    ],
    "products": [
        {
            "code": "R560",
            "name": "Rosa Vibrante",
            "slug": "rosa-vibrante",
            "family": 7,
            "R": 162,
            "G": 33,
            "B": 95,
            "products": [
                1,
                3,
                4,
                5,
                6,
                7,
                9,
                11,
                12,
                13,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24
            ],
            "skuId": 9,
            "composition": {
                "newPrices": {
                    "base1": 1,
                    "tinter1": 1,
                    "tinter2": 1,
                    "tinter3": 1,
                    "tinter4": 1,
                    "tinter5": 0,
                    "tinter6": 0,
                    "tinter7": 0,
                    "tinter8": 0,
                    "tinter9": 0,
                    "tinter10": 0,
                    "tinter11": 0
                },
                "oldPrices": {
                    "base1": 1,
                    "tinter1": 2,
                    "tinter2": 2,
                    "tinter3": 2,
                    "tinter4": 2,
                    "tinter5": 0,
                    "tinter6": 0,
                    "tinter7": 0,
                    "tinter8": 0,
                    "tinter9": 0,
                    "tinter10": 0,
                    "tinter11": 0
                }
            }
        },
        {
            "code": "R560",
            "name": "Rosa Vibrante",
            "slug": "rosa-vibrante",
            "family": 7,
            "R": 162,
            "G": 33,
            "B": 95,
            "products": [
                1,
                3,
                4,
                5,
                6,
                7,
                9,
                11,
                12,
                13,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24
            ],
            "skuId": 45580,
            "composition": {
                "newPrices": {
                    "base1": 2,
                    "tinter1": 2,
                    "tinter2": 2,
                    "tinter3": 2,
                    "tinter4": 2,
                    "tinter5": 0,
                    "tinter6": 0,
                    "tinter7": 0,
                    "tinter8": 0,
                    "tinter9": 0,
                    "tinter10": 0,
                    "tinter11": 0
                },
                "oldPrices": {
                    "base1": 1,
                    "tinter1": 2,
                    "tinter2": 2,
                    "tinter3": 2,
                    "tinter4": 2,
                    "tinter5": 0,
                    "tinter6": 0,
                    "tinter7": 0,
                    "tinter8": 0,
                    "tinter9": 0,
                    "tinter10": 0,
                    "tinter11": 0
                }
            }
        }
    ],
    "productType": [
        {
            "id": 4,
            "name": "Tinta alba Família Protegida Acetinado",
            "slug": "tinta-alba-familia-protegida-acetinado"
        },
        {
            "id": 5,
            "name": "Tinta alba Clássica Fosco Aveludado",
            "slug": "tinta-alba-classica-fosco"
        }
    ]
}