import { defineMessages } from 'react-intl'

const prefix = 'admin/admin.app.clone-promotions.';

export const titlesIntl = defineMessages({
  pageTitle: { id: `${prefix}title` },
  accountsTitle: { id: `${prefix}accounts` },
  storesTitle: { id: `${prefix}stores` },
  buttonPromotion: { id: `${prefix}buttonPromotions` },
  active: { id: `${prefix}active` },
  paused: { id: `${prefix}paused` },
  show: { id: `${prefix}show` },
  duplicatePromotions: { id: `${prefix}duplicatePromotions` },
  status: { id: `${prefix}status` },
  name: { id: `${prefix}name` },
  affectedItem: { id: `${prefix}affectedItem` },
  effects: { id: `${prefix}effects` },
  from: { id: `${prefix}from` },
  to: { id: `${prefix}to` },
  duplicate: { id: `${prefix}duplicate` },
  emptyStoreSelected: { id: `${prefix}emptyStoreSelected` },
  btnShowProducts: { id: `${prefix}btnShowProducts` },
  products: { id: `${prefix}products` },
  emptyProducts: { id: `${prefix}emptyProducts` },
  error: { id: `${prefix}error` },
  errorPromotion: { id: `${prefix}errorPromotions` },
  errorDuplicate: { id: `${prefix}errorDuplicate` },
  successDuplicate: { id: `${prefix}successDuplicate` },
  errorSelectDuplicate: { id: `${prefix}errorSelectDuplicate` },
  selectAllPromotions: { id: `${prefix}selectAllPromotions` },
  noPromotions: { id: `${prefix}noPromotions`},
  checkboxAlertTitle: { id: `${prefix}checkboxAlertTitle`},
  checkboxAlertDescription: { id: `${prefix}checkboxAlertDescription`},
  checkboxAlertBtnCancel: { id: `${prefix}checkboxAlertBtnCancel`},
  checkboxAlertBtnAccept: { id: `${prefix}checkboxAlertBtnAccept`},
  warningDuplicateAllSellers: { id: `${prefix}warningDuplicateAllSellers` },
  duplicatePromotionsAllSellers: { id: `${prefix}duplicatePromotionsAllSellers` },
  duplicatePromotionsSomeSellers: { id: `${prefix}duplicatePromotionsSomeSellers` },
  duplicateButtonText: { id: `${prefix}buttonTextDuplicate` },
  warningDuplicateSelectSellers: { id: `${prefix}warningDuplicateSlectedSellers` },
  duplicatePromotionsSomeSellersHelp: {id: `${prefix}duplicatePromotionsSomeSellersHelp`},
  duplicatePromotionsLableTextArea: { id: `${prefix}duplicatePromotionsLableTextArea` },
  backButtonText: { id: `${prefix}buttonBack`},
})