mutation updateSkusPrices($tinter1: Float!, $tinter2: Float!, $tinter3: Float!, $tinter4: Float!, $tinter5: Float!, $tinter6: Float!, $tinter7: Float!, $tinter8: Float!, $tinter9: Float!, $tinter10: Float!, $tinter11: Float!,$tinter12: Float!, $tinter13: Float!, $oldPrices: Boolean) {
    updateSkusPrices(tinter1: $tinter1, tinter2: $tinter2, tinter3: $tinter3, tinter4: $tinter4, tinter5: $tinter5, tinter6: $tinter6, tinter7: $tinter7, tinter8: $tinter8, tinter9: $tinter9, tinter10: $tinter10, tinter11: $tinter11, tinter12: $tinter12, tinter13: $tinter13, oldPrices: $oldPrices)
}
